name: Debug Build

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev

      - name: Install frontend dependencies
        run: yarn install --network-timeout 100000

      - name: Check project structure
        run: |
          echo "=== Project structure ==="
          ls -la
          echo "=== src-tauri directory ==="
          ls -la src-tauri/
          echo "=== Cargo.toml content ==="
          head -20 src-tauri/Cargo.toml
          echo "=== tauri.conf.json content ==="
          head -20 src-tauri/tauri.conf.json

      - name: Check Tauri CLI
        run: |
          echo "=== Yarn tauri version ==="
          yarn tauri --version
          echo "=== Tauri info ==="
          yarn tauri info

      - name: Build with Tauri
        run: |
          echo "=== Starting Tauri build ==="
          yarn tauri build --verbose 