name: Simple Build

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]

jobs:
  build:
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev

      - name: Install dependencies
        run: yarn install --network-timeout 100000

      - name: Install Tauri CLI
        run: echo "Using existing Tauri CLI from package.json"

      - name: Build frontend
        run: |
          echo "Building frontend..."
          yarn run web:build
          echo "Frontend build complete"

      - name: Debug Tauri setup
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Contents of src-tauri directory:"
          ls -la src-tauri/ || echo "src-tauri directory not found"
          echo "Looking for Cargo.toml:"
          find . -name "Cargo.toml" -type f
          echo "Checking if src-tauri/Cargo.toml exists:"
          if [ -f "src-tauri/Cargo.toml" ]; then
            echo "src-tauri/Cargo.toml exists"
          else
            echo "src-tauri/Cargo.toml does not exist"
          fi
          echo "Checking Tauri CLI version:"
          yarn tauri --version
          echo "Checking .gitignore for src-tauri exclusions:"
          grep -n "src-tauri" .gitignore || echo "No src-tauri entries in .gitignore"
          
      - name: Tauri build
        run: |
          echo "Building with yarn tauri build..."
          yarn tauri build --verbose 