name: Debug Build

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev

      - name: Install frontend dependencies
        run: yarn install --network-timeout 100000

      - name: Check project structure
        run: |
          echo "=== Project structure ==="
          ls -la
          echo "=== src-tauri directory ==="
          ls -la src-tauri/
          echo "=== Cargo.toml content ==="
          head -20 src-tauri/Cargo.toml
          echo "=== tauri.conf.json content ==="
          head -20 src-tauri/tauri.conf.json

      - name: Check Tauri CLI
        run: |
          echo "=== Yarn tauri version ==="
          yarn tauri --version
          echo "=== Tauri info ==="
          yarn tauri info

      - name: Install Tauri CLI
        run: |
          echo "=== Installing Tauri CLI ==="
          yarn add -D @tauri-apps/cli@latest
          echo "=== Check Tauri CLI installation ==="
          yarn tauri --version

      - name: Try manual web build
        run: |
          echo "=== Building frontend manually ==="
          yarn run web:build
          echo "=== Checking dist directory ==="
          ls -la dist/ || echo "dist directory not found"
          echo "=== Checking build config ==="
          cat src-tauri/tauri.conf.json | grep -A5 -B5 "distDir"

      - name: Try Tauri build manually
        run: |
          echo "=== Trying Tauri build with yarn ==="
          yarn tauri build --verbose
        continue-on-error: true

      - name: Try Tauri build with cargo
        run: |
          echo "=== Installing Tauri CLI via cargo ==="
          cargo install tauri-cli --version "^1.0"
          echo "=== Cargo Tauri version ==="
          cargo tauri --version
          echo "=== Building with cargo tauri ==="
          cargo tauri build --verbose
        continue-on-error: true

      - name: Build with Tauri Action (if manual fails)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: debug-v__VERSION__
          releaseName: 'Debug v__VERSION__'
          releaseBody: 'Debug build for troubleshooting.'
          releaseDraft: true
          prerelease: true 